// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG20o4k9ZwyAP8Y8S7B1rwRFRK1TTNSHE',
    appId: '1:290979462186:web:b28a67eb905a30d01f1753',
    messagingSenderId: '290979462186',
    projectId: 'reimage',
    authDomain: 'reimage.firebaseapp.com',
    storageBucket: 'reimage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0N75KyY9TjHPcjL9rXb3jZVKpfEbm11Y',
    appId: '1:290979462186:android:93a88b6c0d78089f1f1753',
    messagingSenderId: '290979462186',
    projectId: 'reimage',
    storageBucket: 'reimage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeB3PaaIjeNlGXpmg_SLXuiyuLPM7AAZE',
    appId: '1:290979462186:ios:8b0cc381bbfcd65b1f1753',
    messagingSenderId: '290979462186',
    projectId: 'reimage',
    storageBucket: 'reimage.firebasestorage.app',
    iosBundleId: 'com.revision.org.my-app.dev',
  );

}